# Generated by Django 6.0.5 on 2026-05-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('Classes', '0001_initial'),
        ('Rooms', '0001_initial'),
        ('Schools', '0001_initial'),
        ('Subjects', '0001_initial'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.classlevel')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to='Teachers.teacher')),
                ('default_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rooms.room')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.division')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='LessonAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_periods', models.PositiveIntegerField(default=1)),
                ('requires_double_period', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetables.classsection')),
                ('default_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rooms.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timetable_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.academicyear')),
                ('bell_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.bellschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Timetables.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetables.classsection')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.day')),
                ('lesson_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Timetables.lessonallocation')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rooms.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetables.timetable')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetables.timetableversion')),
            ],
        ),
    ]
