# Generated by Django 6.0.5 on 2026-05-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='bell_schedule',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='status',
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timetable_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20),
        ),
    ]
