# Generated by Django 6.0.5 on 2026-05-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetables', '0002_remove_timetable_bell_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='timetable_type',
            field=models.CharField(choices=[('PRE-PRIMARY', 'Pre-Primary'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('SENIOR-SECONDARY', 'Senior-Secondary')], max_length=20),
        ),
    ]
