# Generated by Django 6.0.5 on 2026-05-13 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
        ('Subjects', '0002_alter_subject_section_type'),
        ('Teachers', '0001_initial'),
        ('Timetables', '0003_alter_timetable_timetable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id_value', models.CharField(max_length=50)),
                ('day_name', models.CharField(max_length=50)),
                ('period_id_value', models.CharField(max_length=50)),
                ('period_name', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetables.classsection')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rooms.room')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Timetables.timetable')),
            ],
            options={
                'unique_together': {('timetable', 'class_section', 'day_id_value', 'period_id_value')},
            },
        ),
    ]
