# Generated by Django 6.0.5 on 2026-05-17 08:25

from django.db import migrations, models


def remove_duplicate_lesson_allocations(apps, schema_editor):
    LessonAllocation = apps.get_model("Timetables", "LessonAllocation")
    duplicate_keys = {}

    for allocation in LessonAllocation.objects.order_by("id").values(
        "id",
        "school_id",
        "academic_year_id",
        "class_section_id",
        "subject_id",
    ):
        key = (
            allocation["school_id"],
            allocation["academic_year_id"],
            allocation["class_section_id"],
            allocation["subject_id"],
        )
        duplicate_keys.setdefault(key, []).append(allocation["id"])

    delete_ids = []
    for ids in duplicate_keys.values():
        if len(ids) > 1:
            delete_ids.extend(ids[:-1])

    if delete_ids:
        LessonAllocation.objects.filter(id__in=delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_day_day_type_period_day_type'),
        ('Classes', '0002_alter_classlevel_section_type'),
        ('Rooms', '0001_initial'),
        ('Schools', '0001_initial'),
        ('Subjects', '0003_teachersubjectcapability_class_sections'),
        ('Teachers', '0001_initial'),
        ('Timetables', '0005_teacherdailystatus_lectureadjustment'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_lesson_allocations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(fields=('school', 'class_level', 'division'), name='unique_class_section_per_school_level_division'),
        ),
        migrations.AddConstraint(
            model_name='lessonallocation',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'class_section', 'subject'), name='unique_lesson_allocation_per_class_subject_year'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('timetable', 'teacher', 'day_id_value', 'period_id_value'), name='unique_teacher_per_timetable_period'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('timetable', 'room', 'day_id_value', 'period_id_value'), name='unique_room_per_timetable_period'),
        ),
    ]
