# Generated by Django 6.0.5 on 2026-05-18 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetables', '0006_classsection_unique_class_section_per_school_level_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_sections', models.ManyToManyField(blank=True, related_name='timetable_configurations', to='Timetables.classsection')),
                ('timetable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='Timetables.timetable')),
            ],
        ),
    ]
