# Generated by Django 6.0.5 on 2026-05-18 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_day_day_type_period_day_type'),
        ('Timetables', '0007_timetableconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableconfiguration',
            name='bell_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_configurations', to='Academic.bellschedule'),
        ),
        migrations.AddField(
            model_name='timetableconfiguration',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='timetable_configurations', to='Academic.period'),
        ),
        migrations.AddField(
            model_name='timetableconfiguration',
            name='working_days',
            field=models.ManyToManyField(blank=True, related_name='timetable_configurations', to='Academic.day'),
        ),
    ]
