# Generated by Django 6.0.5 on 2026-05-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
        ('Timetables', '0008_timetableconfiguration_bell_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableconfiguration',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='timetable_configurations', to='Teachers.teacher'),
        ),
    ]
