# Generated by Django 6.0.5 on 2026-05-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
        ('Timetables', '0009_timetableconfiguration_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableconfiguration',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='timetable_configurations', to='Rooms.room'),
        ),
    ]
