# Generated by Codex on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


def scope_existing_allocations(apps, schema_editor):
    LessonAllocation = apps.get_model("Timetables", "LessonAllocation")
    Timetable = apps.get_model("Timetables", "Timetable")

    for allocation in LessonAllocation.objects.order_by("id"):
        timetables = list(
            Timetable.objects.filter(
                school_id=allocation.school_id,
                academic_year_id=allocation.academic_year_id,
            ).order_by("id")
        )
        if not timetables:
            continue

        allocation.timetable_id = timetables[0].id
        allocation.save(update_fields=["timetable"])

        for timetable in timetables[1:]:
            LessonAllocation.objects.create(
                school_id=allocation.school_id,
                timetable_id=timetable.id,
                academic_year_id=allocation.academic_year_id,
                class_section_id=allocation.class_section_id,
                subject_id=allocation.subject_id,
                teacher_id=allocation.teacher_id,
                default_room_id=allocation.default_room_id,
                weekly_periods=allocation.weekly_periods,
                requires_double_period=allocation.requires_double_period,
                is_active=allocation.is_active,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("Timetables", "0010_timetableconfiguration_rooms"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonallocation",
            name="unique_lesson_allocation_per_class_subject_year",
        ),
        migrations.AddField(
            model_name="lessonallocation",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_allocations",
                to="Timetables.timetable",
            ),
        ),
        migrations.RunPython(scope_existing_allocations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="lessonallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("timetable__isnull", False)),
                fields=("timetable", "class_section", "subject"),
                name="unique_lesson_allocation_per_timetable_class_subject",
            ),
        ),
    ]
