# Generated by Codex on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Academic", "0003_academic_timetable_scope"),
        ("Timetables", "0012_classsection_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="Academic.academicyear",
            ),
        ),
    ]
