# Generated by Django 6.0.5 on 2026-05-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('COMPUTER_LAB', 'Computer Lab'), ('SCIENCE_LAB', 'Science Lab'), ('LIBRARY', 'Library'), ('PLAYGROUND', 'Playground'), ('ACTIVITY_ROOM', 'Activity Room')], default='CLASSROOM', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
    ]
