# Generated by Codex on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Rooms", "0001_initial"),
        ("Timetables", "0011_lessonallocation_timetable_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="Timetables.timetable",
            ),
        ),
    ]
