# Generated by Codex on 2026-05-17

from django.db import migrations, models


def normalize_senior_secondary(apps, schema_editor):
    ClassLevel = apps.get_model("Classes", "ClassLevel")
    ClassLevel.objects.filter(section_type=" Senior-Secondary").update(
        section_type="Senior-Secondary"
    )


def denormalize_senior_secondary(apps, schema_editor):
    ClassLevel = apps.get_model("Classes", "ClassLevel")
    ClassLevel.objects.filter(section_type="Senior-Secondary").update(
        section_type=" Senior-Secondary"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("Classes", "0002_alter_classlevel_section_type"),
    ]

    operations = [
        migrations.RunPython(
            normalize_senior_secondary,
            denormalize_senior_secondary,
        ),
        migrations.AlterField(
            model_name="classlevel",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("Pre-Primary", "Pre-Primary"),
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("Senior-Secondary", "Senior-Secondary"),
                ],
                max_length=20,
            ),
        ),
    ]
