# Generated by Codex on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Classes", "0003_normalize_senior_secondary_section_type"),
        ("Timetables", "0011_lessonallocation_timetable_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="classlevel",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_levels",
                to="Timetables.timetable",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="Timetables.timetable",
            ),
        ),
    ]
