# Generated by Django 6.0.5 on 2026-05-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('school', models.CharField(max_length=180, verbose_name='School or institute')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry_type', models.CharField(choices=[('demo', 'Book product demo'), ('pricing', 'Pricing and plan details'), ('implementation', 'Implementation support'), ('technical', 'Technical support'), ('enterprise', 'Enterprise or partnership query')], max_length=30)),
                ('institution_size', models.CharField(blank=True, choices=[('1-25', '1-25 teachers'), ('26-75', '26-75 teachers'), ('76-150', '76-150 teachers'), ('150+', '150+ teachers')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact enquiry',
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
