"""
Django settings for AI_TIMETABLE_SAAS project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t(tssa_^(b_(0t!y84ryj^&qg6zywyqh*y9t^wo0io$-#uw!uz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project Apps
    'Accounts',
    'Schools',
    'Subscriptions',
    'Academic',
    'Classes',
    'Teachers',
    'Subjects',
    'Rooms',
    'Timetables',
    'Reports',
    'Notifications',
    'WebsiteApp',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'AI_TIMETABLE_SAAS.tenancy.SchoolTenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AI_TIMETABLE_SAAS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Accounts.context_processors.school_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'AI_TIMETABLE_SAAS.wsgi.application'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "school_dashboard"
LOGOUT_REDIRECT_URL = "login"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


def _sqlite_tenant_databases():
    """
    SQLite has no separate schemas, so development isolation uses one database
    file per school/tenant. Example: SCHOOL_SQLITE_TENANTS=school_1,school_2
    """
    
    tenant_dir = BASE_DIR / "tenant_dbs"
    tenant_databases = {}

    for raw_alias in os.environ.get("SCHOOL_SQLITE_TENANTS", "").split(","):
        alias = raw_alias.strip()
        if not alias:
            continue

        tenant_databases[alias] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": tenant_dir / f"{alias}.sqlite3",
        }

    return tenant_databases


DATABASES.update(_sqlite_tenant_databases())
SCHOOL_TENANT_DATABASES = tuple(alias for alias in DATABASES if alias != "default")
SCHOOL_TENANT_APPS = (
    "Schools",
    "Academic",
    "Classes",
    "Teachers",
    "Subjects",
    "Rooms",
    "Timetables",
)
DATABASE_ROUTERS = ["AI_TIMETABLE_SAAS.db_router.SchoolTenantDatabaseRouter"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'




# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'prameshwar4378@gmail.com'  # Replace with your Gmail email address
EMAIL_HOST_PASSWORD = 'ktty kqsv xsvf ggpd'  # Replace with your Gmail password or App Password
