# Generated by Django 6.0.5 on 2026-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_type',
            field=models.CharField(choices=[('WEEKDAY', 'Weekday'), ('SATURDAY', 'Saturday')], default='WEEKDAY', max_length=20),
        ),
        migrations.AddField(
            model_name='period',
            name='day_type',
            field=models.CharField(choices=[('WEEKDAY', 'Monday to Friday'), ('SATURDAY', 'Saturday')], default='WEEKDAY', max_length=20),
        ),
    ]
