# Generated by Codex on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Academic", "0002_day_day_type_period_day_type"),
        ("Timetables", "0012_classsection_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_year_setups",
                to="Timetables.timetable",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="Timetables.timetable",
            ),
        ),
        migrations.AddField(
            model_name="bellschedule",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bell_schedules",
                to="Timetables.timetable",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="Timetables.timetable",
            ),
        ),
    ]
