# Generated by Django 6.0.5 on 2026-05-12 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0001_initial'),
        ('Timetables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetables.timetable')),
            ],
        ),
    ]
