# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("TRIALING", "Trialing"),
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past Due"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                default="TRIALING",
                max_length=20,
            ),
        ),
    ]
