# Generated by Codex on 2026-05-14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schools", "0001_initial"),
        ("Subscriptions", "0002_schoolsubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsubscription",
            name="auto_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolsubscription",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="schoolsubscription",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolsubscription",
            name="provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="schoolsubscription",
            name="provider_subscription_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="schoolsubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="allow_ai_generation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly"), ("CUSTOM", "Custom")],
                default="MONTHLY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="schoolsubscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Subscriptions.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="BillingCustomer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("billing_name", models.CharField(max_length=255)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("billing_phone", models.CharField(blank=True, max_length=20)),
                ("billing_address", models.TextField(blank=True)),
                ("gst_number", models.CharField(blank=True, max_length=30)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("provider_customer_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_customer",
                        to="Schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("provider_invoice_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="Schools.school",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="Subscriptions.schoolsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("-issue_date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("NET_BANKING", "Net Banking"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="MANUAL",
                        max_length=30,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=255)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("provider_payment_id", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="Subscriptions.invoice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="Schools.school",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="Subscriptions.schoolsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("-paid_at", "-created_at", "-id"),
            },
        ),
    ]
