# Generated by Django 6.0.5 on 2026-05-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='section_type',
            field=models.CharField(choices=[('Pre-Primary', 'Pre-Primary'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('Senior-Secondary', ' Senior-Secondary'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
    ]
