# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Subjects", "0002_alter_subject_section_type"),
        ("Timetables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachersubjectcapability",
            name="class_sections",
            field=models.ManyToManyField(blank=True, to="Timetables.classsection"),
        ),
    ]
