# Generated by Codex on 2026-05-17

from django.db import migrations, models


def normalize_senior_secondary(apps, schema_editor):
    Subject = apps.get_model("Subjects", "Subject")
    Subject.objects.filter(section_type=" Senior-Secondary").update(
        section_type="Senior-Secondary"
    )


def denormalize_senior_secondary(apps, schema_editor):
    Subject = apps.get_model("Subjects", "Subject")
    Subject.objects.filter(section_type="Senior-Secondary").update(
        section_type=" Senior-Secondary"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("Subjects", "0003_teachersubjectcapability_class_sections"),
    ]

    operations = [
        migrations.RunPython(
            normalize_senior_secondary,
            denormalize_senior_secondary,
        ),
        migrations.AlterField(
            model_name="subject",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("Pre-Primary", "Pre-Primary"),
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("Senior-Secondary", "Senior-Secondary"),
                    ("BOTH", "Both"),
                ],
                default="BOTH",
                max_length=20,
            ),
        ),
    ]
