# Generated by Codex on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Subjects", "0004_normalize_senior_secondary_section_type"),
        ("Timetables", "0011_lessonallocation_timetable_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="Timetables.timetable",
            ),
        ),
        migrations.AddField(
            model_name="teachersubjectcapability",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_subject_capabilities",
                to="Timetables.timetable",
            ),
        ),
    ]
